# Generated by Django 3.2.23 on 2024-02-03 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upcomingblogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="upcomingblog",
            options={"ordering": ["release_date"]},
        ),
    ]
